name: "AI-Engine v2 CI (disabled)"

# Workflow retained for historical reference. All triggers have been removed so it no
# longer executes. Delete this file entirely if you no longer need to consult it.

on: {}

jobs:
  noop:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "noop" 