name: "Auto Update French News (disabled)"

# Legacy v1 workflow kept only for historical reference.
on: {}

jobs:
  noop:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "noop" 