name: Auto Update French News – v3

on:
  schedule:
    - cron:  '0 * * * *'  # Re-enabled - V3 handles root site
  workflow_dispatch:  # Manual trigger for testing

# Allow this workflow to push commits back to the repository.
permissions:
  contents: write
  actions: write      # allow this workflow to trigger other workflows if needed
  pages: write        # allow pushing to gh-pages
  id-token: write     # required by GH Pages action

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BF_PER_RUN_CAP: 10
      BF_DAILY_CAP: 9999
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e ./ai_engine_v3

      - name: Run pipeline
        run: |
          python -m ai_engine_v3.scripts.fetch_news
          python -m ai_engine_v3.scripts.qualify_news

      - name: Commit & push results to main
        run: |
          git config --global user.email "bot@betterfrench.io"
          git config --global user.name "BetterFrenchBot"
          # Skip repository pre-commit hooks (daily-note requirement) for automated runs
          git config --global core.hooksPath /dev/null

          git add ai_engine_v3/data ai_engine_v3/website || true
          if ! git diff --cached --quiet; then
            # --no-verify bypasses any remaining hooks that might be inherited
            git commit -m "chore(pipeline): hourly auto-update" --no-verify
            git push
          fi

      - name: Deploy V3 to GitHub Pages (Root Site) 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ai_engine_v3/website
          force_orphan: true
          commit_message: 'chore(deploy): V3 basic articles update' 