name: Auto Update French News – v2

on:
  schedule:
    # Every 2 hours between 06:00–22:00 Paris time (UTC+1 winter / UTC+2 DST)
    - cron: '0 4-20/2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libxml2-dev libxslt1-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download fr_core_news_sm
          python -m spacy download en_core_web_sm

      - name: Export OpenRouter key
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: echo "OPENROUTER_API_KEY=$OPENROUTER_API_KEY" >> $GITHUB_ENV

      - name: Run AI-Engine v2 pipeline (limit 20)
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python -m ai_engine_v2.pipeline.runner --limit 20 --backfill-limit 20

      - name: Commit & push new rolling feed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ai_engine_v2/data/live/*.json ai_engine_v2/website/rolling_articles*.json || true
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-update v2: fresh articles & site feed" --no-verify
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 