name: QA Smoke Test

on:
  pull_request:
  push:
    branches: [ ai-improve, main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || ! startsWith(github.head_ref, 'ai-engine-v4-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Start local server
        run: |
          python -m http.server 8010 --directory Project-Better-French-Website &
          echo "Server started in background"

      - name: Wait for server
        run: sleep 5

      - name: Run smoke test
        run: python qa/local/test_smoke.py http://localhost:8010

      - name: Run accessibility audit
        run: python qa/local/test_accessibility.py http://localhost:8010 